spring.application.name=api-gateway

server.port=8085

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.example.apigateway=DEBUG

# USER-SERVICE
spring.cloud.gateway.routes[0].id=user_service_direct
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# CLIENT-SERVICE
spring.cloud.gateway.routes[1].id=client_service_direct
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/clients/** 