DROP TABLE IF EXISTS clients;

CREATE TABLE clients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(255) NOT NULL,
    birth_day DATE NOT NULL,
    passport_serial VARCHAR2(4) NOT NULL,
    passport_number VARCHAR2(7) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_passport ON clients (passport_serial, passport_number); 