-- Drop tables if they exist
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(255)
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    role_id NUMBER,
    is_blocked NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key constraint
ALTER TABLE users ADD CONSTRAINT fk_users_roles 
FOREIGN KEY (role_id) REFERENCES roles(id);

-- Insert default roles with Oracle-compatible syntax
INSERT INTO roles (name, description) 
SELECT 'admin', 'Administrator' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'admin');

INSERT INTO roles (name, description) 
SELECT 'user', 'Regular User' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'user'); 