DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS client_products;

-- Products table to store available products
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(500),
    is_available NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Client Products table to track which clients have which products
CREATE TABLE client_products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    product_name VARCHAR2(255) NOT NULL,
    account_number VARCHAR2(20) NOT NULL,
    issue_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Indexes for better performance
CREATE INDEX idx_client_id ON client_products(client_id);
CREATE INDEX idx_product_id ON client_products(product_id);
CREATE UNIQUE INDEX idx_client_product ON client_products(client_id, product_id); 