DROP TABLE IF EXISTS client_offer_reactions;
DROP TABLE IF EXISTS client_offers;

CREATE TABLE client_offers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER NOT NULL,
    offer_text VARCHAR2(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_client_id ON client_offers (client_id);

CREATE TABLE client_offer_reactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id NUMBER NOT NULL,
    reaction_type VARCHAR2(20) NOT NULL, -- ACCEPTED, REFUSED, PENDING
    reaction_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_client_offer FOREIGN KEY (offer_id) REFERENCES client_offers(id),
    CONSTRAINT ck_reaction_type CHECK (reaction_type IN ('ACCEPTED', 'REFUSED', 'PENDING'))
);

CREATE INDEX idx_offer_id ON client_offer_reactions (offer_id); 